import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const neueMontrealFont = localFont({
  src: [
    {
      path: '../fonts/NeueMontreal-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/NeueMontreal-Bold.otf',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-neue-montreal'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={neueMontrealFont.variable}>
      <body className={`${neueMontrealFont.className} antialiased`} style={{backgroundColor: 'rgb(236, 231, 225)'}}>
        <Sidebar />
        <main className="flex-1 ml-24">
            {children}
        </main>
      </body>
    </html>
  );
}