import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SmoothScrolling from "@/components/SmoothScrolling";



const neueMontrealFont = localFont({
  src: [
    {
      path: '../fonts/NeueMontreal-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/NeueMontreal-Bold.otf',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-neue-montreal'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={neueMontrealFont.variable}>
      <body className={`${neueMontrealFont.className} app-body antialiased overflow-x-hidden`}>
        <SmoothScrolling />
        <Sidebar />
        <main className="lg:pt-0 min-h-screen w-full overflow-x-hidden">
          {children}
          
        </main>
      </body>
    </html>
  );
}